-- Initial schema of the online shop. Hibernate only validates it (ddl-auto=validate); Flyway owns every change.

CREATE TABLE categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)             NOT NULL,
    description VARCHAR(500),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Category names are unique regardless of letter case
CREATE UNIQUE INDEX ux_categories_name_lower ON categories (LOWER(name));

CREATE TABLE products (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku            VARCHAR(32)              NOT NULL,
    name           VARCHAR(150)             NOT NULL,
    description    VARCHAR(2000),
    price          NUMERIC(12, 2)           NOT NULL,
    stock_quantity INTEGER                  NOT NULL,
    category_id    BIGINT                   NOT NULL REFERENCES categories (id),
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_products_price_positive CHECK (price > 0),
    CONSTRAINT ck_products_stock_not_negative CHECK (stock_quantity >= 0)
);

CREATE UNIQUE INDEX ux_products_sku_lower ON products (LOWER(sku));
CREATE INDEX ix_products_category_id ON products (category_id);

CREATE TABLE orders (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name    VARCHAR(100)             NOT NULL,
    customer_email   VARCHAR(254)             NOT NULL,
    shipping_address VARCHAR(300)             NOT NULL,
    status           VARCHAR(20)              NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_orders_status CHECK (status IN ('NEW', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED'))
);

CREATE INDEX ix_orders_status ON orders (status);
CREATE INDEX ix_orders_customer_email_lower ON orders (LOWER(customer_email));

-- Order lines are values owned by the order. product_id has no foreign key on purpose:
-- name and price are copied at order time, so history survives deletion of the product.
CREATE TABLE order_items (
    order_id     BIGINT         NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    line_no      INTEGER        NOT NULL,
    product_id   BIGINT         NOT NULL,
    product_name VARCHAR(150)   NOT NULL,
    unit_price   NUMERIC(12, 2) NOT NULL,
    quantity     INTEGER        NOT NULL,
    PRIMARY KEY (order_id, line_no),
    CONSTRAINT ck_order_items_quantity_positive CHECK (quantity > 0)
);

CREATE INDEX ix_order_items_product_id ON order_items (product_id);
